
# profile(로컬 서버 환경)
spring.profiles: properties-local

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  config: classpath:config/logback-spring-local.xml
  file:
    name: logExample
    path: ./data/logs
mca:
  url: http://192.168.114.11:18211/http/lvaca-fmec
open.api: 
  url: http://data.ekape.or.kr/openapi-data/service/user
  serviceKey: 7vHI8ukF3BjfpQW8MPs9KtxNwzonZYSbYq6MVPIKshJNeQHkLqxsqd1ru5btfLgIFuLRCzCLJDLYkHp%2FvI6y0A%3D%3D
---
# profile(개발 서버 환경)
spring.profiles: properties-develop

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  config: classpath:config/logback-spring-develop.xml
  file:
#    name: NHLVA_LOG
#    path: /logs/nhlva/nhlva
    name: logExample
    path: /home/phps/data/logs
mca:
  url: http://192.168.114.11:18211/http/lvaca-fmec
open.api: 
  url: http://data.ekape.or.kr/openapi-data/service/user
  serviceKey: 7vHI8ukF3BjfpQW8MPs9KtxNwzonZYSbYq6MVPIKshJNeQHkLqxsqd1ru5btfLgIFuLRCzCLJDLYkHp%2FvI6y0A%3D%3D
  
---
# profile(상용 서버 환경)
spring.profiles: properties-production

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  config: classpath:config/logback-spring-develop.xml
  file:
    name: logExample
    path: /home/phps/data/logs
#    name: NHLVA_LOG
#    path: /logs/nhlva/nhlva
mca:
  url: http://192.168.97.141:18211/http/lvaca-fmec
open.api: 
  url: http://data.ekape.or.kr/openapi-data/service/user
  serviceKey: 7vHI8ukF3BjfpQW8MPs9KtxNwzonZYSbYq6MVPIKshJNeQHkLqxsqd1ru5btfLgIFuLRCzCLJDLYkHp%2FvI6y0A%3D%3D