jwt:
  secret: jwtsecretkey
cript:
  key: aaaaaaaaaabbbbbb
  iv: aaaaaaaaaabbbbbb
  
# op
# mca.ip=http://192.168.97.141:18211/http/lvaca-fmec
# dev
mca:
  url: http://192.168.114.11:18211/http/lvaca-fmec
  
server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      tracking-modes: cookie
      timeout: 600m
    encoding:
      charset: UTF-8
      force: true
spring:
  application:
    name: Auction
  profiles:
    active: local
#    active: develop
#    active: production
    include:
      - database
      - properties
    service-name: tibero
  resources:
    chain:
      cache: false
      enabled: true
      html-application-cache: true
      strategy:
        content:
          enabled: true
          paths:
            - /static/**
      compressed: true
    static-locations: classpath:/static/**
    add-mappings: true
  security:
    user:
      name: test
      password: test
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
  messages:
    basename: messages/message
    encoding: UTF-8
    cache-duration: 3600
#    static-path-pattern: /static/**

mybatis:
  config-location: classpath:database/mybatis-config.xml
  mapper-locations: classpath:database/mapper/**/*Mapper.xml

ncloud:
  storage:
    end-point: https://kr.object.ncloudstorage.com
    region-name: kr-standard
    access-key: loqHvgq2A4WGx0D7feer
    secret-key: yrmIJmsF37g1BExQXk5CIhrMn1EG1h32qJyaTvzF
    bucket-name: test-tt12

---
# local profile(개발자 환경)
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
spring.profiles: local
spring.profiles.include:
  - database-local
  - properties-local
---
# develop profile(개발 서버 환경)
spring.profiles: develop
spring.profiles.include:
  - database-develop
  - properties-develop
---
# production profile(상용 서버 환경)
spring.profiles: production
spring.profiles.include:
  - database-production
  - properties-production
