/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ishift.auction;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.servlet.ServletComponentScan;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
import org.springframework.scheduling.annotation.EnableScheduling;

@EnableScheduling
@ServletComponentScan
@SpringBootApplication
public class SpringBootWebApplication extends SpringBootServletInitializer {
}
